### ISSUE TITLE
Lack of key feature: The user doesn't have a way to change their username

### ISSUE THREAD

**Issue by sarbak** [egeozin/KodKoda#30]
The sign-up process doesn't ask for a username. Afterwards, there doesn't seem to be a way to change it either

<img width="1203" alt="Screen Shot 2020-08-25 at 9 29 32 AM" src="https://user-images.githubusercontent.com/7543678/91180467-bfd38180-e6b5-11ea-80e5-80fa528560af.png">

**Comment by egeozin** [comment]
Added in 2652e4c
