### ISSUE TITLE
Hakkimizda/Ulasin page doesn't work

### ISSUE THREAD

**Issue by sarbak** [egeozin/KodKoda#31]
Right now, it goes to 404. 
For the time being, it could potentially go to Readme which may include a few sentences about the project and the contact information or the github handles of the people.

<img width="595" alt="Screen Shot 2020-08-25 at 9 32 56 AM" src="https://user-images.githubusercontent.com/7543678/91180741-0cb75800-e6b6-11ea-9077-084450967c93.png">

**Comment by egeozin** [comment]
Fixed in c7367b
