### ISSUE TITLE
Interactions with the answers didn't count consistently

### ISSUE THREAD

**Issue by sarbak** [egeozin/KodKoda#33]
When I tried to upvote my own answer or add emojis, it had weird interactions

![chrome-capture (1)](https://user-images.githubusercontent.com/7543678/91181557-168d8b00-e6b7-11ea-99c6-7fb91341e013.gif)

![chrome-capture](https://user-images.githubusercontent.com/7543678/91181561-18efe500-e6b7-11ea-8674-bfcb23d62ae9.gif)

**Comment by sarbak** [comment]
A similar thing happened with the questions as well.

![chrome-capture (2)](https://user-images.githubusercontent.com/7543678/91181810-610f0780-e6b7-11ea-9f1d-cc6997c09991.gif)

**Comment by egeozin** [comment]
@sarbak Could you try this again? 4bb5a50 might have resolved this issue, if it persists, a bit more detail on when does it do that indefinite count would be great. Upvoting answers is coming soon, so it's fine for now.

**Comment by egeozin** [comment]
Fixed
