### ISSUE TITLE
The user handle links go nowhere

### ISSUE THREAD

**Issue by sarbak** [egeozin/KodKoda#34]
When I click on the user's handle link, it gives an error page.

Maybe, for the time being, those links can be de-activated until user-specific profile pages are built.

![chrome-capture (3)](https://user-images.githubusercontent.com/7543678/91182123-c105ae00-e6b7-11ea-9227-211f9be4270d.gif)

**Comment by egeozin** [comment]
Fixed in 1b9bc32
