### ISSUE TITLE
When I was crafting an answer, someone else submitted an answer and my screen crashed

### ISSUE THREAD

**Issue by sarbak** [egeozin/KodKoda#35]
I was writing an answer, it suddenly crashed and all my progress was lost. I saw Ege's answer submitted and thought it might be because of that somehow.

I tried to reproduce it. I started writing an answer and then on another page, I submitted another answer. It crashed again. 

![chrome-capture (4)](https://user-images.githubusercontent.com/7543678/91182962-e3e49200-e6b8-11ea-8de5-2610c2acf979.gif)

**Comment by egeozin** [comment]
@sarbak 4bb5a50 might have fixed this issue, could you try this again?
