### ISSUE TITLE
Code snippets and quotes don't work in questions

### ISSUE THREAD

**Issue by sarbak** [egeozin/KodKoda#37]
When I tried to submit a question that has a code snippet in it, it didn't get formatted as such.

![chrome-capture (5)](https://user-images.githubusercontent.com/7543678/91183685-c4019e00-e6b9-11ea-9aed-eaa3842eecc9.gif)

**Comment by sarbak** [comment]
The same is true for quotes as well

![chrome-capture 6](https://user-images.githubusercontent.com/7543678/91184197-5ace5a80-e6ba-11ea-9694-c71c2946c184.gif)

**Comment by egeozin** [comment]
Fixed in 4bb5a50
