### ISSUE TITLE
When I attempt to upvote (without authorization), it takes to an empty Auth page

### ISSUE THREAD

**Issue by sarbak** [egeozin/KodKoda#39]
If I click to upvote a question on the homepage, before signing up, it sends me to an empty Auth page. I would rather have a page that asks me to sign up or something.

<img width="981" alt="Screen Shot 2020-08-25 at 10 07 50 AM" src="https://user-images.githubusercontent.com/7543678/91184692-ea740900-e6ba-11ea-826b-749e8a1c1c92.png">

**Comment by sarbak** [comment]
When I try to add reactions/emojis to a question, it sends me to a more proper Auth page, but I would like to have some explanation of what just happened and why I am asked to sign in.

<img width="943" alt="Screen Shot 2020-08-25 at 10 09 54 AM" src="https://user-images.githubusercontent.com/7543678/91184937-3626b280-e6bb-11ea-9e85-010363e0245a.png">

**Comment by sarbak** [comment]
When I try to upvote a question, once I am on the question page, it doesn't ask me to do any auth.

![chrome-capture (6)](https://user-images.githubusercontent.com/7543678/91185117-68d0ab00-e6bb-11ea-88dd-9e602f72cf8e.gif)

**Comment by egeozin** [comment]
1 and 3 is fixed in 6bd9b14
