### ISSUE TITLE
Both "Giris Yap" and "Uye Ol" seem to be re-directing to the same page

### ISSUE THREAD

**Issue by sarbak** [egeozin/KodKoda#40]
Both of the links send to the same URL. 

<img width="807" alt="Screen Shot 2020-08-25 at 10 13 15 AM" src="https://user-images.githubusercontent.com/7543678/91185378-c107ad00-e6bb-11ea-9107-7f688c0a1e37.png">

Everything works fine afterwards though. If I have an account, it leads me to Sign-in. If not, it leads me to Create Account.

Maybe "Uye Ol" can include more explanation about why someone needs to sign up

**Comment by egeozin** [comment]
Fixed as this might be a potential enhancement.
