### ISSUE TITLE
Konu başlığı oylama sonrası oyu geri çekememe sorunu

### ISSUE THREAD

**Issue by furkantolgayuce** [egeozin/KodKoda#49]
![image](https://user-images.githubusercontent.com/3485194/92475207-b08c2200-f1e5-11ea-83e2-3e7988f29b71.png)

Konu içerisinde veya anasayfada bir konu başlığına +1 oy kullandıktan sonra verdiğim oyu geri çekemiyorum.

**Comment by egeozin** [comment]
Fixed in e9e5be5
