### ISSUE TITLE
Açılan konu içerisinde sonsuz emoji gönderme

### ISSUE THREAD

**Issue by furkantolgayuce** [egeozin/KodKoda#50]
Konu içerisinde istediğim okey emojisi gönderebiliyorum. Sayfa yenilendiğinde hepsi sıfırlanıyor. Diğer emojilerde oylama düzgün çalışıyor.

![Screen record from 2020-09-08 15 20 00](https://user-images.githubusercontent.com/3485194/92475954-e1b92200-f1e6-11ea-9a20-aebfcb727732.gif)

**Comment by egeozin** [comment]
Fixed in c7fc3a0
