### ISSUE TITLE
Yorum bıraktıktan sonra yorum input alanının temizlenmemesi

### ISSUE THREAD

**Issue by furkantolgayuce** [egeozin/KodKoda#51]
![image](https://user-images.githubusercontent.com/3485194/92476026-ff868700-f1e6-11ea-9ebb-cbafac74914b.png)

Yukarıdaki gibi bir yorum yaptıktan sonra yorumum aşağıya geliyor fakat aynı zamanda input alanında kalmaya devam ediyor.

**Comment by egeozin** [comment]
Fixed in 587dd63
