### ISSUE TITLE
Emoji kullanımı sonrasında oyu geri çekememe sorunu

### ISSUE THREAD

**Issue by furkantolgayuce** [egeozin/KodKoda#52]
Konu içerisinde konu gövdesi veya yapılan yorum için bir emoji kullandığımda verdiğim oyu/emojiyi geri çekemiyorum.

![image](https://user-images.githubusercontent.com/3485194/92476549-cf8bb380-f1e7-11ea-9e81-22509f9a4a9f.png)

**Comment by egeozin** [comment]
Fixed in e9e5be5
