### ISSUE TITLE
Cevap sayacının eş zamanlı güncellenmemesi

### ISSUE THREAD

**Issue by furkantolgayuce** [egeozin/KodKoda#53]
Bir konuya yorum/cevap atıldığı zaman cevap sayacı eş zamanlı güncellenmiyor.

![Screen record from 2020-09-08 15 32 37](https://user-images.githubusercontent.com/3485194/92477137-bcc5ae80-f1e8-11ea-9731-af9c86b3cfd9.gif)

**Comment by egeozin** [comment]
Fixed in 01462b7
